[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scratch_syntax"
version = "0.6.0"
authors = [
  { name="Cade", email="cadey.matignas@gmail.com" },
]
description = "A syntax library designed to help scratch users transition to python"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
Homepage = "https://github.com/cadeymatignas-source/scratch_syntax"